module euler1
import [std std.io]

std.io.println "Euler 1";
let before: std.i64 = std.io.time ();

let sum: std.i32 = 0;
let x: std.i32 = 1000;

while (x > 1) {
	x = x - 1;

	let y: std.i32 = x % 5;
	let z: std.i32 = x % 3;

	if (y == 0 || z == 0) {
		sum = sum + x;
	};
};

std.io.println std.to_string sum;

let after: std.i64 = std.io.time ();
std.io.print std.to_string ((std.to_f32 (after - before)) / (std.to_f32 1000000));
std.io.println " ms";
