module test
import [std std.io]

fn main: () -> () = \() => {
	let start: [std.ui64; 2] = [1, 2];

	let fib: ([std.ui64; 2], std.ui64, std.ui64) -> std.ui64 = \(arr, acc, max) => {
		let next: std.ui64 = (arr!!0) + (arr!!1);
		if (next > max)	{
			acc
		} else {
			let next_arr: [std.ui64; 2] = [arr!!1, next];
			if (next % 2 == 0) { acc = acc + next; };
			fib (next_arr, acc, max)
		}
	};

	std.io.print (fib ([1, 2], 2, 4000000));
	()
};