[package]
name = "supervisor"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
simple_logger = "2.3"
log = "0.4"
crossbeam-channel = "0.5.6"
galevm = { path="../vm/vm" }